apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: http3-test
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-http3-test
    helm.sh/chart: traefik-26.0.0
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: 34.89.71.52
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-http3-test
  ports:
  - port: 80
    name: "web"
    targetPort: web
    protocol: TCP
  - port: 443
    name: "websecure"
    targetPort: websecure
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: traefik-http3
  namespace: http3-test
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-http3-test
    helm.sh/chart: traefik-26.0.0
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: 34.89.71.52
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-http3-test
  ports:
  - port: 443
    name: "websecure-http3"
    targetPort: websecure-http3
    protocol: UDP